os:
  - linux
  - osx
  - windows

language: c

env:
  - BRANCH=1.0.4

cache:
  directories:
    - "$HOME/.choosenim"
    - "$TRAVIS_BUILD_DIR/git"

install:
  # Use common Travis script maintained as a gist
  # https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/3122ece117489afcc9008b63d6278d97074b8f2c/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - nimble install -y -d
  - nim c src/choosenim
  - nimble test
  - yes | choosenim stable # Workaround tester overwriting our Nimble install.
  - export VERSION="$(./bin/choosenim --version | cut -f2,2 -d' ' | sed 's/v//')"
  - export EXT=""
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export EXT=".exe"; fi
  - export OSNAME="$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OSNAME="macosx"; fi
  - export ARCH="amd64"
  - mv "bin/choosenim${EXT}" "bin/choosenim-${VERSION}_${OSNAME}_${ARCH}_debug${EXT}"
  - nimble build -d:release
  - mv "bin/choosenim${EXT}" "bin/choosenim-${VERSION}_${OSNAME}_${ARCH}${EXT}"
  - ls -l bin

notifications:
  irc: "chat.freenode.net#nimbuild"

deploy:
  provider: releases
  api_key:
    secure: "BFVHT2lvgvW2tYRn1tVs+7YnSNXYLVCF6EFQBbR/Q4CJ/L+Se6+S4MCNYnz+h4Pb9cGGTNKdmG1bdJi1150UwH6TMlYYTDn1XBmf6SnZ3Q91Xu4Zr1Cpd+25wUvRPNWGkj2DPNSR84Dr4E2ElgpJ4XzohbutBejSPasdCzTeduhetB+G5EcH7qwMhOm4gnVnZP4/tzSugU4eJUCQBjnTJbhepFlA/j/Dyf29Nsd5fSaeYS4W5ffu9rRN8Kxrz0cMw7hHknzZyZnF5XcaFebtZOif7EpAdXnuKphbgX48MacrLQ318RAdI0YRsTyh1UBydGOMxa606yaFCqucTHVDw/RjdaGjS2ZiOZfN6/nWvkPKysbuNpXmXH9FVUutaX3VJhJX2dZBVu3t24YlZLS+772h500HAmBCGlU56mgiz4SnldJVzrschl/JlYfOEdXjXQAi7q/avUS0zSoiVqP0Vmq2TCMAeIn49UBRivRKk9p4PIwonKnbqd/SPKEWQ7V95VLcwz1ic7eeHhPrfmVTw84+VuBYqVB8pThtCc0jlLBpRoGX5a82Xr1ma7cwLTBDWWT/W/n/JUpvB3+nNNKu08IV1zg/6Vb4+s+qX/NHceDu2G/3vla3CiEb+FGBSlfebHNXmyHvEx69Ag+xJLb7pRkVcW2paEEOaOKTSCYmUXQ="
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: iranika/choosenim
